export interface Itext {
    __charBounds?:any;
    __corner?:any;
    _fontSizeMult:number;
    _measuringContext:any;
    _styleProperties:any[];
    absolutePositioned:boolean;
    aCoords:any;
    angle:number;
    backgroundColor:string;
    borderColor:string;
    borderDashArray:any[];
    borderOpacityWhenMoving:number;
    borderScaleFactor:number;
    cacheProperties:any[];
    caching:boolean;
    centeredRotation:boolean;
    centeredScaling:boolean;
    charSpacing:number;
    clipPath:any;
    clipTo:Function;
    cornerColor:string;
    cornerDashArray:any[];
    cornerSize:number;
    cornerStrokeColor:string;
    cornerStyle:string;
    cursorColor:string;
    cursorDelay:number;
    cursorDuration:number;
    cursorWidth:number;
    deltaY :number;
    dirty :boolean;
    editable :boolean;
    editingBorderColor :string;
    evented :boolean;
    excludeFromExport :boolean;
    fill :string;
    fillRule :string;
    flipX :boolean;
    flipY :boolean;
    fontFamily :string;
    fontSize :number;
    fontStyle :string;
    fontWeight :any;
    globalCompositeOperation :string;
    hasBorders :boolean;
    hasControls :boolean;
    hasRotatingPoint :boolean;
    height :number;
    hoverCursor :string;
    includeDefaultValues :boolean;
    inverted :boolean;
    isEditing :boolean;
    left :number;
    lineHeight :number;
    linethrough :boolean;
    lockMovementX :boolean;
    lockMovementY :boolean;
    lockRotation :boolean;
    lockScalingFlip :boolean;
    lockScalingX :boolean;
    lockScalingY :boolean;
    lockSkewingX :boolean;
    lockSkewingY :boolean;
    lockUniScaling :boolean;
    MIN_TEXT_WIDTH :number;
    minScaleLimit :number;
    moveCursor :string;
    noScaleCache :boolean;
    objectCaching :boolean;
    opacity :number;
    originX :string;
    originY :string;
    overline :boolean;
    padding :number;
    paintFirst :string;
    perPixelTargetFind :boolean;
    rotatingPointOffset :number;
    scaleX :number;
    scaleY :number;
    selectable :boolean;
    selectionBackgroundColor :string;
    selectionColor :string;
    selectionEnd :number;
    selectionStart :number;
    shadow :any;
    skewX :number;
    skewY :number;
    statefullCache :boolean;
    stateProperties :any[];
    stroke :string;
    strokeDashArray :any[];
    strokeDashOffset :number;
    strokeLineCap :string;
    strokeLineJoin :string;
    strokeMiterLimit :number;
    strokeWidth :number;
    styles :any;
    subscript :any;
    superscript :any;
    textAlign :string;
    textBackgroundColor :string;
    top :number;
    transformMatrix :any[];
    transparentCorners :boolean;
    type :string;
    underline :boolean;
    visible :boolean;
    width :number;
}

export interface ITextDimensions{
    width:any;
    height:any;
    zoomX:any;
    zoomY:any;
}

export interface ITextCloneImageOpts{
    format?:string;
    quality?:number;
    multiplier?:number;
    left?:number;
    top?:number;
    width?:number;
    height?:number;
    enableRetinaScaling?:boolean;
    withoutTransform?:boolean;
    withoutShadow?:boolean;
}