export interface CanvasInterface {
    allowTouchScrolling?:boolean;
    altActionKey?:string;
    altSelectionKey?:string;
    backgroundVpt?:boolean;
    centeredKey?:string;
    centeredRotation?:boolean;
    centeredScaling?:boolean;
    clipTo?: Function;
    containerClass?:string;
    controlsAboveOverlay?:boolean;
    defaultCursor?:string;
    enableRetinaScaling?:boolean;
    fireMiddleClick?:boolean;
    fireRightClick?:boolean;
    freeDrawingCursor?:string;
    FX_DURATION?:number;
    hoverCursor?:string;
    imageSmoothingEnabled?:boolean;
    includeDefaultValues?:boolean;
    interactive?:boolean;
    isDrawingMode?:boolean;
    moveCursor?:string;
    notAllowedCursor?:string;
    overlayVpt?:boolean;
    perPixelTargetFind?:boolean;
    preserveObjectStacking?:boolean;
    renderOnAddRemove?:boolean;
    rotationCursor?:string;
    selection?:boolean;
    selectionBorderColor?:string;
    selectionColor?:string;
    selectionDashArray?: any[];
    selectionFullyContained?:boolean;
    selectionKey?: string | any[];
    selectionLineWidth?:number;
    skipOffscreen?:boolean;
    skipTargetFind?:boolean;
    snapAngle?:number;
    snapThreshold?:null|number;
    stateful?:boolean;
    stopContextMenu?:boolean;
    svgViewportTransformation?:boolean;
    targetFindTolerance?:number;
    uniScaleKey?:string;
    uniScaleTransform?:boolean;
    viewportTransform?: any[];
}
